In [3]:
import numpy as np
myarr=np.array([3,4,5,6,7])
# myarr
myarr=np.array([3,2,1,4],np.int64) #given a datatype int with 64 bits
myarr



array([3, 2, 1, 4], dtype=int64)

In [9]:
myarr=np.array([[1,2,3,4]])
myarr.shape  #will give output no. of row and column

(1, 4)

In [8]:
myarr.dtype #will give the data type 

dtype('int32')

In [10]:
myarr[0,3]

4

In [12]:
myarr[0,3]=45 #changes the value to 45
myarr

array([[ 1,  2,  3, 45]])

In [13]:
#array creation
#1)conversion from other python structures
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
listarray.dtype

dtype('int32')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size


9

In [17]:
np.array({23,34,45})

array({34, 45, 23}, dtype=object)

In [18]:
#2)Intricsic numpy array creation objects
zeros=np.zeros((2,1,6))
zeros

array([[[0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.]]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 1, 6)

In [21]:
rng=np.arange((15))
rng  #gives a numpy and not a list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace=np.linspace(1,5,12)#will give 1 to 5 no. with 12 space
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
lspace=np.linspace(1,10,12)#will give 1 to 5 no. with 12 space
lspace

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [24]:
emp=np.empty((4,6))#gives empty array of 4,6 and all the elements will be random and afterwards if we want any value we can assign from it
emp

array([[1.36729081e-311, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.30276956e+180],
       [6.00736842e-067, 3.67137505e+097, 1.69421691e-052,
        3.41846039e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        4.50353809e+174, 3.27054238e+179, 4.46439557e-090],
       [4.31244568e-033, 2.59027860e-144, 1.16442250e-028,
        9.44872517e-143, 6.17582057e-322, 2.08610860e-308]])

In [25]:
emp_like=np.empty_like(lspace)#purane array ka size copy krke ek nya array bna deta h
emp_like

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [26]:
ide=np.identity(45)
ide #gives identity matrix of 45X45

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3,33)
#arr.reshape(3,31)--->will through error as it cant be divided in equal parts

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr.ravel()#agai converts the 2darray into 1d (normal array) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.shape

(99,)

In [33]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis=0) #AXIS 0= Y axis,AXIS 1= x axis

array([12, 15, 18])

In [36]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [38]:
ar.T #transpose of the array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
ar.flat

In [42]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
8
9


In [44]:
ar.ndim #no. of dimension

2

In [46]:
ar.size

9

In [49]:
ar.nbytes #shows the the total bytes consumed

36

In [51]:
one=np.array([1,2,3,4])
one.argmax() #gives the index where the max element is present

3

In [53]:
one.argmin()

0

In [56]:
one.argsort() #sorts the index no. in ascending order


array([0, 1, 2, 3], dtype=int64)

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar.argmin()

0

In [62]:
ar.argmax()

8

In [64]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [66]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [68]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [70]:
ar.ravel

<function ndarray.ravel>

In [73]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
ar2=np.array([[1,1,1],[2,1,3],[3,4,2]])
ar2

array([[1, 1, 1],
       [2, 1, 3],
       [3, 4, 2]])

In [79]:
ar+ar2

array([[ 2,  3,  4],
       [ 6,  6,  9],
       [10, 12, 11]])

In [81]:
ar*ar2

array([[ 1,  2,  3],
       [ 8,  5, 18],
       [21, 32, 18]])

In [83]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [85]:
ar.sum()

45

In [87]:
ar.min()

1

In [89]:
ar.max()

9

In [92]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [97]:
type(np.where(ar>5))

tuple

In [99]:
np.count_nonzero(arr) #count the none zero element


98

In [101]:
np.nonzero(ar)  # hr dimension ke liye tuple dega  

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
#doc.scipy ki website pr sare methods ek bari acche se dekh lena